---
title: "Data Wrangling Methods"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


|            |            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/swordfern)|[Data](https://jmhulbert.github.io/swordfern/data)|[Methods](https://jmhulbert.github.io/swordfern/methods)|[Analyses](https://jmhulbert.github.io/swordfern/analyses)|[Discussion](https://jmhulbert.github.io/swordfern/discussion)|[Maps](https://jmhulbert.github.io/swordfern/maps)
|             |           |            |            |            |            |

|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[oomycete](https://jmhulbert.github.io/swordfern/analyses/oomycete)|[illumina](https://jmhulbert.github.io/swordfern/analyses/illumina)|[greenhouse-plants](https://jmhulbert.github.io/swordfern/plants)|[iNaturalist](https://jmhulbert.github.io/swordfern/analyses/inaturalist/)|
|             |           |            |            |


## Data Wrangle

### Combine isolate data with iNat data

```{r}
sites <- read.csv("https://github.com/jmhulbert/swordfern/raw/refs/heads/main/data/field/sword.fern.field.sample.data.csv")
isolates <- read.csv("https://github.com/jmhulbert/swordfern/raw/refs/heads/main/data/lab/sword.fern.isolates.csv")
extractions <- read.csv("https://github.com/jmhulbert/swordfern/raw/refs/heads/main/data/lab/sword.fern.isolate.extractions.august.csv")
```

### Combined greenhouse data
```{r}
#greenhouse.weights <- read.csv("./data/greenhouse/Final.Root.Weights.csv")
#greenhouse.fronds <- read.csv("./data/greenhouse/Final.Frond.Counts.csv")
#greenhouse <- left_join(greenhouse.fronds,greenhouse.weights,by="Fern.Number")
#write.csv(greenhouse,"Final-Greenhouse-Data-Combined.csv",row.names=FALSE)
#greenhouse <- read.csv("./data/greenhouse/Final-Greenhouse-Data-Combined.csv")
```


```{r}
intersect(names(isolates), names(extractions))
```

```{r}
isolates <- isolates[-c(1,3,15:29)]
```


```{r}
extractions <- extractions %>% filter(Sample.Extraction.Number!="FHL0167")
```



```{r}
results <- left_join(isolates,extractions,join_by("Isolate.ID"=="Isolate.Name"))
```


```{r}
results <- results %>% mutate(Isolate.ID2=Isolate.ID) %>% separate(Isolate.ID2, into=c("Sample", "Isolate Number"), sep="-")
```


```{r}
results <- left_join(results,sites,join_by("Sample"=="Sample.ID"))
```


```{r}
#write.csv(results,file="/Users/professorbabykangaroo/Library/Mobile Documents/com~apple~CloudDocs/Core/Server Files/swordfern/data/lab/combined.results.csv")
```

