---
title: "Methods"
output: html_document
date: "2025-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Field Collections

### iNat Questions

iNaturalist Questions
  +	Fern Heath Conditions
    +	Good, fair, poor, dead, unsure, other
  +	Percent Dieback (0 is healthy, 100 is dead)
  +	Fern Symptom
    +	Browning 
    +	Wilting
+	Collapse of individual fronds
+	Dead
+ Absence of new growth
+ Multiple symptoms (list in notes)
+ Other ____
+	Surrounding Fern Conditions: 
+ Percent Dieback of surrounding ferns
+ Similar symptoms? 
+ Absence of regeneration?
+	Hydrology
+ Wetland/stream/flooded area
+ Upland/well drained
+	Urban, natural, managed, or a mix.
+	Site Description
+ Top of slope, bottom of ravine, mid slope, etc.
+	Disturbance level
+	GPS location



### Sample Methods

A guide for collecting samples is available at: https://foresthealth.org/wp-content/uploads/2024/08/Sword-Fern-Field-Sampling-Protocolv2.pdf

Sword Fern Root Sample Methods
Root samples were collected from healthy and unhealthy plants at 3-4 locations
+	Mercer Island – roots collected on October 28, 2024
+ Collected from all plants
+	Seward Park – roots from healthy and unhealthy plants collected on October 28, 2024
+ Did we collect roots from all?
+	Bainbridge Island (Fort Ward, Blakely cemetery, Blakely harbor) – only roots from dying plants collected in Jan 24 2025
+ Roots only collected from dying plants, n+ dead roots taken
+ Fort ward: 3 sites, all unhealthy
+ Blakely Cemetery: 2 Sites, all unhelathy
+ Blakely Harbor: 1 Site, unhealthy
+	Eatonville (Marshall Falls) Feb 10 2025
+ Only 2 root samples or all?
+ 1 site, unhealthy
+	Kitsap Peninsula (Seabeck) – roots from healthy and unhealthy plants collected (but only 1 site, 3 plants was considered healthy – double check) on Feb 17, 2025
+ Roots collected from all samples
+ 6 sites, 3 health, 3 unhealthy
+	Mirrormont (Issaquah) - roots from healthy and unhealthy plants collected on Feb 21, 2025
+ 4 sites: 2 healthy, 2 unhealthy
+	Belfair – roots from healthy and unhealthy plants collected on Feb 27, 2025
+ 4 sites: all unhealthy
+	Issaquah (Swamp Trail)- roots from healthy and unhealthy plants collected on March 3, 2025
+ 4 sites, 1 healthy, 3 unhealthy
+	Mercer Island (Luther Burbank site 1)- roots from healthy and unhealthy plants collected on March 3, 2025
+ 1 site, unhealthy
+	Port Ludlow- roots from healthy and unhealthy plants collected on March 4, 2025
+ 4 sites: all unhealthy
+	Mercer Island (Luther burbank site 2)- roots from healthy and unhealthy plants collected on March 13, 2025
+ 1 site, unhealthy
+	Seward Park
+ 4 sites: all unhealthy

Roots were stored in the fridge (6C?) until washed
Soil and litter were washed from roots
Small parts of roots were cut and placed int+ 2 screw cap tubes (2 tubes per sample)
Cut roots in screwcap tubes were stored in freezer (-20c?) 

Roots from 5 plants from Kitsap Peninsula were plated directly int+ PARPH on Feb 20, 2025 (3 days after collection)

Roots from 10 plants were collected from a private property in mirrormont on Feb 21, 2025
Roots were placed in the fridge on Feb 22, 2025

### Locations



## Greenhouse Trials

### Potted Plants

Greenhouse Trials Methods
+	Six 5-gallon buckets (hence forth referred as buckets) of soil were collected from Seward Park (11/12/24)
+	Seward Park Soil was mixed on 11/21/24
+	Soil was divided int+ treatments
+ Sterilized Soil: 3 buckets of Seward soil were added t+ Pro-Grow Electric Soil Sterilizer and heated t+ 80C for 1hour (11/22/24)
+ Seward Soil Wild: 3 buckets of Seward soil were set aside for mixing
+	Soil was mixed with potting soil at 2:1 rati+ (Six buckets of potting mix t+ three buckets of wild and sterilized soil
+ However, we previously cooked 3 buckets of potting mix, and we split it between soil mixes (~11/18/24)
	1.5 buckets of previously sterilized potting mix
	4.5 buckets of potting soil
	3 buckets of treated or untreated Seward soil
+	Soil was added t+ bait trays for baiting before and after treatment soil 
+ 250g of soil were added t+ three soil bait trays each
+ 3 bait trays before sterilization
+ 3 bait trays after sterilization-mixed with potting soil
+ Greenhouse tap water was added t+ the soil bait trays
+ Rhododendron leaves were added t+ the the surface of the water (9/22/24)
+	45 ferns were potted in each of the soil mixes (11/22/24)
+ Ferns were organized t+ alternate between wild soil and sterilized soil. 
+ 2 tables were set up with an irrigation line down the middle of the table that had 12 emitters with four-way connectors on each emitter.
	48 lines are on each table
	On each four-way emitter is 2 ferns in wild soil and 2 ferns in sterilized soil.
	At the first, sixth, and last emitter on each table, one of the four-way splitters is watering int+ a bucket t+ monitor watering
+	Ferns were watered after potting for 20 minutes (~20 ounces of water)
+ The irrigation timer was set t+ water the ferns every 12 hours for 10 minutes 
	~10 ounces of water, twice a day
+ Irrigation times were adjusted t+ xx
+	Fern condition recorded (11/27/24)
+ Health condition
+	Good
+	Fair
+	Poor
+	Dead
+ Percent of foliage browning
+ Notes
+	Where plant is starting t+ brown
+	Abnormalities
+	Spotting

Greenhouse environmental controls and power returned on 12/4/2024
Watering was switched t+ 30 minutes each interval. However, water was turned off
Water was turned back on 12/8/2024 with 20 minute intervals starting at 11am.

Temp was originally set t+ 68-76 and 63-76, but we adjusted it t+ lower high temp before fans kick on as below

Temperature in greenhouse set to:
+	Daytime: 68-74 F
+	Nighttime: 63-74 F
Lighting set t+ turn on <= 120 W/m^2, 5 min delay, 30 W/m^2 differential from 7 AM t+ 6 PM only 
Soil moisture measurement sensors were placed on opposite sides of water influx, 2 more were added on 12/9/24
Trial 2
+	Six 5-gallon buckets of soil were collected from Seward Park (12/11/24)
+	Seward Park Soil was mixed on (12/17/24)
+	Soil was divided int+ treatments:
+ Sterilized Soil: 3 buckets of Seward soil were added t+ Pro-Grow Electric Soil Sterilizer and heated t+ 80C for 1hour on (12/17/24)
	 total time in soil sterilizer was 3 hours and 35 minutes
+ Seward Soil Wild: 3 buckets of Seward soil were set aside for mixing
+	Soil was mixed with potting soil at a 1:1 rati+ three buckets of potting mix t+ three buckets of wild and sterilized soil.
+	44 ferns were potted in each of the sterilized and wild soil mixes (12/18/24) 
+	18 additional ferns were potted in purely potting soil for control. (12/18/24)
+	Ferns were organized t+ alternate between wild soil, sterilized soil and controlled soil or water
+	2 tables were set up with an irrigation line down the middle of the table that had 14 emitters with four-way connectors on each emitter. 
+	Each table has 3 buckets t+ collect water and assure that emitters are dripping properly.
+	Soil was added t+ bait trays for baiting before and after treatment soil 
+ 3 bait trays before sterilization
+ 3 bait trays after sterilization-mixed 
+ Greenhouse tap water was added t+ the soil bait trays
+ Rhododendron leaves were added t+ the surface of the water (12/18/24)
+ Baits were removed and plated ont+ PARPHV8 in January
+ Secondary isolations were made from growth out of baits
+ Plates without any growth representative of oomycetes were discarded
+ DNA was extracted from isolates that were originally subcultured on PARPHV8 and transferred t+ PDA
+ DNA was extracted with prepman ultra extractions by scraping mycelia from surface of PDA plates
+	Fern condition recorded (12/19/24)
+ Health condition
	Good
	Fair
	Poor
	Dead
+ Percent of foliage browning
+ Notes
	Where plant is starting t+ brown
	Abnormalities
	Spotting
+	
Watering
+	Ferns were watered for 20 minutes every 12 hours until February 5th, 2025.
+	On February 5th, 2025, water schedule was changed t+ 5 minutes every 12 hours. 
+	Watering was changed t+ 5 minutes per 24 hours on Feb 10, 2025 because plants were still fully saturated on above water regime (5 minutes per 12 hours as of Feb 5, 2025). Plants were receiving 4oz per day. 
+	Watering was changed t+ 5 minutes per 48 hours on Feb 18, 2025 because plants were still fully saturated (with the exception of 8 day dry period – three watering events skipped -- Feb 22, Feb 24, and Feb 26)
+ Plants received 4oz on Feb 18, 2025
+ Plants did not receive water on Feb 19, 2025
+ Plants received 4oz on Feb 20, 2025
+ Water was shut off for the weekend t+ allow plants t+ dry out a bit (Feb 22 and Feb 24 watering skipped)
+ Plants did not receive water on Feb 25, 2025
+ Plants did not receive water on Feb 26
+	Water schedule changed t+ 5 minutes every 72 hrs on Feb 26
+ Watering resumed on Feb 28, plants received 4 oz
+ Plants received 4 oz on March 3
+ Plants received 4 oz on March 6
+ Plants received 4 oz on March 9 Sunday
+ Plants received 4 oz on March 12 Wednesday
+ Plants received 4 oz on March 15 – Saturday
+ Plants received 4 oz on March 18 – Tuesday?

(NOTE Changes were made without ‘resetting’ because of Rain Drip Model: R675CT Manual indicates: “Programming Changes - If you avoid the RESET position, Frequency and Run Time dial settings can be made at any time and will not change your original start time. (ref). The changes t+ the dial did lower the watering frequency. 

Watering schedule remained the same through Winter and Spring. June 10th – still on 72 hours
The shade cloth was closed on June 2nd
On June 10th, the water pump – cooling pad pump 2 was turned on and instructed t+ turn on at 78 degrees F
On June 10th, the stage 1 cooling (fan 1) was changed t+ turn on at 72 degrees f (was previously set at 74). 



Measurements
+	Meter data downloaded on Feb 5, 2025
+	Poromoter data was collected on x number of random fern pairs and x number of ferns in potting soil on February 5, 2025
+	Poromoter data was collected on x number of random fern pairs and x number of ferns in potting soil on February 5, 2025
+	Fern conditions were assessed on February 1 ? 
+	The number of healthy and unhealthy fronds were counted on x(30?) fern pairs on xx date? 
+	Poromoter data was collected on February 14, 2025

Feb 10, 2025
Leaves were cut and plated t+ try and determine organism involved in leaf tip browning
Leaves from 6 plants were sampled (3 control, 3 wild) from Trial 1
1 leaf (tiny leaf from single frond/leaflet) was cut from 3 fronds per plant
Small pieces of leaves were cut, surface sterilized and plated in t+ PDA+SC media
Surface sterilization 
All three leaf samples mixed in the following contents then allowed t+ dry
30 seconds in 96% ethanol
30 seconds in 10% bleach
30 seconds in 96% ethanol
Allowed t+ dry in hood




 HOBO Temperature Logger
Channel 1 – blue – in soil, plant number W26
Channel 2 – pink – in air, beneath table in center of table in center row
Channel 3 – yellow – in air, beneath table in front (south side) of table in center row
Channel 4 – new cord, added 10.10.25, in soil of potted plant number C36

August 19, 2025
+	Selected 4 sword ferns from Trial 1: C11, C22, W12, W23 (check numbers)
+	Brushed off excess soil with hands
+	Washed roots with water t+ remove as much soil as possible and clean roots
+	About one plastic bin worth of water
+	Laid out roots t+ compare density
+	One wild sword fern had decreased root density compared t+ other sword ferns
+	Cut root tips from each sword fern using sterilized scissors and tweezers
+ Did not cut thick or green tipped roots (appeared healthy)
+ Majority of roots selected were thin, dry
+ Placed int+ PARPHV8 plates 





#### Conductance data

Sword ferns were planted int+ three soils types 1) wild (positive control), 2) sterilized, and 3) potting mix. Plants were grown in soils in controlled greenhouse environment for 4 months, and water stressed during the last month (Starting Feb 28th). Stomatal conductance was measured 33 plants (9 plants in potting mix, 12 plants and sterilized soil, 12 plants in wild soil) after 40 days (Apirl 9th) of water stress. Stomatal conductance was measured on tw+ healthy fronds per plant and averaged together. 

After confirming the data was fairly normally distributed with visual investigation, an one-way? anova was completed t+ determine if there was evidence for a relationship between stomatal conductance and soil treatment. N+ evidence for a relationship was found (p=0.232, df=30,f=1.533) between treatment and stomatal conductance. 

Within the limited sampling period, there was difference between the treatments in our research question. The lack of evidence for a relationship may be due t+ the small sample size or the ability of sword ferns t+ limit stress t+ individual fronds. Sword ferns produce many fronds and it is unclear if the stomatal conductance of each frond would be affected by a root disease at the same time or individually.


### Rice Inoculations

Swordfern Soil Bait Rice Inoculation

Trial 1:
6/17/25: Rice flasks prepared in a 250 Erlenmeyer flask
+	25 g long grain rice
+	18 mL DI water
+	10, 3mm blank V8 agar plugs
Autoclaved with foil on lid LQ60 settings and left t+ cool at RT overnight

6/18/25: Loosened rice with sterilized large tongs
Autoclaved again on LQ60 settings and let cool at RT

07/30/25: Labeled flasks with following inoculation plan
Flask Species	Isolates Name	Location	Location Type
Blank V8 Agar Control A (BLAA)	N/A	N/A	N/A
Blank V8 Agar Control B (BLAB)	N/A	N/A	N/A
Phytophthora Syringae A (SYRA)	FHL0095	Mercer	Trail
Phytophthora Syringae B (SYRB)	FHL0233	Issaquah	Residential
Phytophthora Syringae C (contaminated)	FHL0095	Mercer	Trail
Phytophthora Plurivora A (PLUA)	FHL0135	Eatonville	Trail
Phytophthora Plurivora B (PLUB)	FHL0185	NRCA	Trail
Phytophthora Cambivora A (CAMA)	FHL0162	Issaquah	Residential
Phytophthora Cambivora B (CAMB)	FHL0161	Issaquah	Residential
Phytophthora Europaea-like (EURA)	FHL0104	Mercer	Trail
Phytophthora Flexuosa-like (FLEX)	FHL0193	Mercer	Trail
Phytophthora Cactorum A (CACA)	FHL0152	Eatonville	Trail
Phytophthora Cactorum B (CACB)	FHL0152	Eatonville	Trail
Phytophthora Occultans A (OCCA)	FHL0140	Zeek's	Urban
Phytophthora Occultans B (OCCB)	FZJ046-1 Soil	Zeek's	Urban
Globisporangium Intermedium A (GINA)	FHL0208	Seward	Trail
Globisporangium Intermedium B (GINB)	FHL0229	Seward	Trail
Globisporangium Intermedium C (GINC)	FZJ127-1 Root	Seward	Trail
N+ Agar, n+ rice (NONE)	N/A	N/A	N/A
Placed all flasks and tools for inoculation in UV light for 30 mins
Adding 10, 3mm plugs of each culture t+ corresponding flask

8/29/25: Inoculated plants with rice flasks



## Baiting Methods

2025 Sword Fern Soil Baiting Methods

2025 Methods
+	500g soils samples were added t+ plastic 6Q bait trays on March 17, 2025
+ 100ml ish of tap water was added t+ dry soils samples t+ wet the soil for 24 hours
+	Bait trays were flooded with tap water halfway on March 18th, 2025 soil all soil was submerged
+	Rhododendron leaves were collected on March 18th and added t+ half flooded samples
+	More water was added on March 19th s+ the bait trays were full
+ Some leaves remained semerged in the water


