---
title: "Swordfern Mortality Sample Analyses - Oomycetes"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 4
    number_sections: true
    fig_width: 10
    fig_height: 6
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load required packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(kableExtra)
library(readr)
library(misty)
library(stringr)
library(BSDA)
library(car)
library(ggpubr)
library(RColorBrewer)
library(pillar)
library(readxl)
library(gridExtra)
library(rstatix)
library(effectsize)
library(npmv)
```


|            |            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/swordfern)|[Data](https://jmhulbert.github.io/swordfern/data)|[Methods](https://jmhulbert.github.io/swordfern/methods)|[Analyses](https://jmhulbert.github.io/swordfern/analyses)|[Discussion](https://jmhulbert.github.io/swordfern/discussion)|[Maps](https://jmhulbert.github.io/swordfern/maps)
|             |           |            |            |            |            |

|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[oomycete](https://jmhulbert.github.io/swordfern/analyses/oomycete)|[illumina](https://jmhulbert.github.io/swordfern/analyses/illumina)|[greenhouse-plants](https://jmhulbert.github.io/swordfern/plants)|[iNaturalist](https://jmhulbert.github.io/swordfern/analyses/inaturalist/)|
|             |           |            |            |

### Import dataset and clean

```{r}
#setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Core/Server Files/swordfern")
#data <- read.csv("~/GitHub/swordfern/data/lab/combined.results.csv")
data <- read.csv("https://github.com/jmhulbert/swordfern/raw/refs/heads/main/data/lab/combined.results.csv")
data <- rename(data,Tentative.Result = Tentative.Results..Internal.NCBI.Oomcycete.including.voucher.blast.)
data <- data %>% filter(common_name.x=="western sword fern")
data$Tentative.Result[data$Tentative.Result=="Phytophthora europaea or abietivora?"] <- "Phytophthora sp."
data$Tentative.Result[data$Tentative.Result=="Phytophthora flexuosa?"] <- "Phytophthora sp."
data$Project <- as.factor(data$Project.x)
data$place_guess.x <- as.factor(data$place_guess.x)
data$Oomycete <- as.factor(data$Oomycete)
roots <- data %>% filter(Project=="Swordfern Roots")
```

## Field Sample Data

### Field Soil Baits

```{r}
field.baits <- data %>% filter(Project=="Swordfern Soil Bait Isolates")
```

#### Number of Isolates

```{r}
ggplot(field.baits[field.baits$Tentative.Result!="" & !is.na(field.baits$Tentative.Result),],aes(Tentative.Result,fill=Genus)) +geom_histogram(stat="count")+coord_flip() +theme_bw() +guides(fill="none") +theme(axis.text = element_text(face = "italic")) + labs(y="Number of Isolates")
```

### Summary Tables

#### Field Sample Collection Overview

```{r warning=FALSE}
sample.summary <- field.baits %>% summarize(n.sites = n_distinct(place_guess.x,na.rm=TRUE),n.samples=n_distinct(Sample),n.isolates=n(),n.oomycete.isolates=sum(Oomycete=="Oomycete",na.rm=TRUE),n.oomycete.spec=n_distinct(Tentative.Result),n.Phytoph.isolates=sum(Genus=="Phytophthora",na.rm=TRUE),n.Phytoph.spec=n_distinct(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),Phytoph.spp=paste(unique(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),collapse=", "))

kable(sample.summary,digits = 2,col.names = c("Number of Sites", "Number of Samples", "Number of Isolates", "Oomycete Isolates", "Oomycete Species", "Phytophthora Isolates", "Number of Phytophthora Species", "Phytophthora Species")) %>% kable_material(c("striped", "hover","condensed")) %>% kable_styling(full_width = F) %>% scroll_box(height = "400px")
```


#### Phytophthora Isolates Overview

```{r warning=FALSE}
Phytophthora.summary <- field.baits %>% filter(Genus=="Phytophthora") %>% summarize(n.sites = n_distinct(place_guess.x,na.rm=TRUE),n.samples=n_distinct(Sample),n.isolates=n(),n.oomycete.isolates=sum(Oomycete=="Oomycete",na.rm=TRUE),n.oomycete.spec=n_distinct(Tentative.Result),n.Phytoph.isolates=sum(Genus=="Phytophthora",na.rm=TRUE),n.Phytoph.spec=n_distinct(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),Phytoph.spp=paste(unique(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),collapse=", "))

kable(Phytophthora.summary,digits = 2, col.names = c("Number of Sites", "Number of Samples", "Number of Isolates", "Oomycete Isolates", "Oomycete Species", "Phytophthora Isolates", "Number of Phytophthora Species", "Phytophthora Species")) %>% kable_material(c("striped", "hover","condensed")) %>% kable_styling(full_width = F) %>% scroll_box(height = "400px")
```



#### Samples per Site

```{r warning=FALSE}
site.summary <- field.baits %>% group_by(place_guess.x) %>% summarize(n.samples=n_distinct(Sample),n.isolates=n(),n.oomycete.isolates=sum(Oomycete=="Oomycete",na.rm=TRUE),n.oomycete.spec=n_distinct(Tentative.Result),n.Phytoph.isolates=sum(Genus=="Phytophthora",na.rm=TRUE),n.Phytoph.spec=n_distinct(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),Phytoph.spp=paste(unique(Tentative.Result[Genus=="Phytophthora" & !is.na(Tentative.Result)]),collapse=", "))
kable(site.summary, digits = 2, col.names = c("Sampling Site", "Number of Samples", "Number of Isolates", "Oomycetes Isolates", "Oomycete Species", "Phytophthora Isolates", "Number of Phytophthora Species", "Phytophthora Species")) %>% kable_material(c("striped", "hover","condensed")) %>% kable_styling(full_width = F) %>% scroll_box(height = "400px")
```

#### Species Summary

```{r warning=FALSE}
species.summary <- field.baits %>% filter(!is.na(Tentative.Result) & Tentative.Result!="") %>% group_by(Tentative.Result) %>% summarize(n.sites = n_distinct(place_guess.x,na.rm=TRUE),n.samples = n_distinct(Sample,na.rm=TRUE),n.isolates=n(),Genus=paste(unique(Genus)))

kable(species.summary, digits = 2,col.names = c("Sample Species", "Number of Sites", "Number of Samples", "Number of Isolates", "Genus")) %>% kable_material(c("striped", "hover","condensed")) %>% kable_styling(full_width = F) %>% scroll_box(height = "400px")
```


```{r warning=FALSE}
ggplot(species.summary,aes(Tentative.Result,n.sites,fill=Genus)) +geom_col() +theme_bw() +coord_flip() + guides(fill=FALSE) +theme(axis.text = element_text(face = "italic")) +labs(x="Species",y="Number of Sites (e.g. Seward Park)")
```

```{r warning=FALSE}
ggplot(species.summary,aes(Tentative.Result,n.samples,fill=Genus)) +geom_col() +theme_bw() +coord_flip() + guides(fill=FALSE) +theme(axis.text = element_text(face = "italic")) +labs(x="Species",y="Number of Samples")
```

```{r warning=FALSE}
species.summary <- field.baits %>% filter(!is.na(Tentative.Result) & Tentative.Result!="") %>% group_by(site.location.description.x,Tentative.Result) %>% summarize(n.sites = n_distinct(place_guess.x,na.rm=TRUE),n.samples = n_distinct(Sample,na.rm=TRUE),n.isolates=n(),Genus=paste(unique(Genus)))
kable(species.summary, digits = 2,col.names = c("Site Type", "Sample Species", "Number of Sites", "Number of Samples", "Number of Isolates", "Genus")) %>% kable_material(c("striped", "hover","condensed")) %>% kable_styling(full_width = F) %>% scroll_box(height = "400px")
```

```{r warning=FALSE}
ggplot(species.summary,aes(Tentative.Result,n.sites,fill=Genus)) +geom_col() +facet_wrap(~site.location.description.x) +theme_bw() +coord_flip() + guides(fill=FALSE) +theme(axis.text = element_text(face = "italic")) +labs(x="Species",y="Number of Sites")
```

```{r warning=FALSE}
ggplot(field.baits,aes(Tentative.Result,percent.of.plants..of.same.species..affected.within.sight.....y ,fill=Genus)) +geom_boxplot()+coord_flip()+theme_bw()+guides(fill="none")
```

```{r warning=FALSE}
ggplot(field.baits,aes(Tentative.Result,Dieback.percent.x,fill=Genus)) +geom_boxplot()+coord_flip()+theme_bw()+guides(fill="none")
```
