---
title: "Sword Fern Mortality Maps"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(patchwork)
library(scales)
library(ggmap)
library(osmdata)
```

```{r}
ggmap::register_google(key = Sys.getenv("GOOGLE_API_KEY"))
```

|            |            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/swordfern)|[Data](https://jmhulbert.github.io/swordfern/data)|[Methods](https://jmhulbert.github.io/swordfern/methods)|[Analyses](https://jmhulbert.github.io/swordfern/analyses)|[Discussion](https://jmhulbert.github.io/swordfern/discussion)|[Maps](https://jmhulbert.github.io/swordfern/maps)
|             |           |            |            |            |            |

|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[oomycete](https://jmhulbert.github.io/swordfern/analyses/oomycete)|[illumina](https://jmhulbert.github.io/swordfern/analyses/illumina)|[greenhouse-plants](https://jmhulbert.github.io/swordfern/plants)|[iNaturalist](https://jmhulbert.github.io/swordfern/analyses/inaturalist/)|
|             |           |            |            |


Note you can add 'keep_md:yes' to the YAML to save all r outputs as images. 

# Purpose

The purpose of this page is to generate maps of data used in analyses. 


# Wrangle

```{r}
data <- read.csv("https://github.com/jmhulbert/swordfern/raw/refs/heads/main/data/lab/combined.results.csv")
```

```{r}
data <- rename(data,Tentative.Result = Tentative.Results..Internal.NCBI.Oomcycete.including.voucher.blast.)
```


```{r}
data <- data %>% filter(common_name.x=="western sword fern") %>% filter(!is.na(latitude.x))
```

```{r}
data$Tentative.Result[data$Tentative.Result=="Phytophthora europaea or abietivora?"] <- "Phytophthora sp."
data$Tentative.Result[data$Tentative.Result=="Phytophthora flexuosa?"] <- "Phytophthora sp."
```

```{r}
data <- data %>%
  mutate(Results.Neg = if_else(
    is.na(Tentative.Result) | Tentative.Result == "",
    "No Oomycete found",
    Tentative.Result
  ))

```


```{r}
Phytophthora <- data %>% filter(Genus=="Phytophthora") %>% droplevels()
```




```{r}
levels(as.factor(data$place_guess.x))
Seward <- data %>% filter(place_guess.x=="Seward Park, Seattle, WA, US") %>% droplevels()
```


# Map


```{r}
sewardbb <- c(left = min(Seward$longitude.x), 
                              bottom = min(Seward$latitude.x), 
                              right = max(Seward$longitude.x), 
                              top = max(Seward$latitude.x))
```


```{r}
seward.map <- get_map(sewardbb, zoom = 16, scale = 2, maptype="satellite",source="google")
```

```{r}
species.map <- ggmap(seward.map)+geom_jitter(data=Seward,aes(x=longitude.x,y=latitude.x,fill=Results.Neg),color = "black",pch=21, size = 3, alpha=0.7,width = 0.00015) + theme_minimal() +labs(title="Sword Fern Mortality Results",x="Longitude",y="Latitude",fill="Species") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) + scale_fill_discrete(labels = function(x) parse(text = paste0("italic('",x, "')")))
```

```{r}
species.map
```


```{r}
syringae.seward.map <- ggmap(seward.map)+geom_point(data=Seward[Seward$Results.Neg=="Phytophthora syringae",],aes(x=longitude.x,y=latitude.x,fill=Results.Neg),color = "black",pch=21, size = 3, alpha=0.7) + theme_minimal() +labs(title="Seward Park",x="Longitude",y="Latitude",fill="Species") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) + scale_fill_discrete(labels = function(x) parse(text = paste0("italic('",x, "')")))
```

```{r}
syringae.seward.map
```



```{r}
databb <- c(left = min(Phytophthora$longitude.x), 
                              bottom = min(Phytophthora$latitude.x), 
                              right = max(Phytophthora$longitude.x), 
                              top = max(Phytophthora$latitude.x))
```


```{r}
data.map <- get_map(databb, zoom = 9, scale = 2, maptype="terrain",source="google")
```

```{r}
species.map <- ggmap(data.map)+geom_point(data=Phytophthora,aes(x=longitude.x,y=latitude.x,fill=Results.Neg),color = "black",pch=21, size = 3) + theme_minimal() +labs(title="Sword Fern Mortality Results",x="Longitude",y="Latitude",fill="Species") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) + scale_fill_discrete(labels = function(x) parse(text = paste0("italic('",x, "')")))
```

```{r}
species.map
```


```{r}
syringaebb <- c(left = min(Phytophthora[Phytophthora$Tentative.Result=="Phytophthora syringae",]$longitude.x),bottom = min(Phytophthora[Phytophthora$Tentative.Result=="Phytophthora syringae",]$latitude.x), right = max(Phytophthora[Phytophthora$Tentative.Result=="Phytophthora syringae",]$longitude.x),top = max(Phytophthora[Phytophthora$Tentative.Result=="Phytophthora syringae",]$latitude.x))
```


```{r}
data.map <- get_map(syringaebb, zoom = 10, scale = 2, maptype="terrain",source="google")
```


```{r}
syringae.map <- ggmap(data.map)+geom_point(data=Phytophthora[Phytophthora$Tentative.Result=="Phytophthora syringae",],aes(x=longitude.x,y=latitude.x,fill=Tentative.Result),color = "black",pch=21, size = 3) + theme_minimal() +labs(title="Phytophthora syringae",x="Longitude",y="Latitude",fill="Species") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) +guides(fill="none")
```

```{r}
syringae.map
```


```{r}
databb <- c(left = min(Phytophthora$longitude.x), 
                              bottom = min(Phytophthora$latitude.x), 
                              right = max(Phytophthora$longitude.x), 
                              top = max(Phytophthora$latitude.x))
```


```{r}
data.map <- get_map(databb, zoom = 9, scale = 4, maptype="terrain",source="google")
```

```{r}
sample.map <- ggmap(data.map)+geom_jitter(data=Phytophthora,aes(x=longitude.x,y=latitude.x,fill="red"),color="black",pch=21,size=3,alpha=0.7,width=0.015) + theme_minimal() +labs(title="Sword Fern Mortality Sample Locations",x="Longitude",y="Latitude") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) +guides(color="none",fill="none")
```

```{r}
sample.map
```


```{r}
field.baits <- Phytophthora %>% filter(Project.x=="Swordfern Soil Bait Isolates")
field.baits <- field.baits %>% filter(latitude.x!="NA") 
databb <- c(left = min(field.baits$longitude.x), 
                              bottom = min(field.baits$latitude.x), 
                              right = max(field.baits$longitude.x), 
                              top = max(field.baits$latitude.x))
```


```{r}
data.map <- get_map(databb, zoom = 9, scale = 4, maptype="terrain",source="google")
```


```{r}
sample.map <- ggmap(data.map)+geom_jitter(data=field.baits,aes(x=longitude.x,y=latitude.x,fill="red"),color="black",pch=21,size=3,alpha=0.7,width=0.015) + theme_minimal() +labs(title="Sword Fern Mortality Sample Locations",x="Longitude",y="Latitude") +theme(plot.title = element_text(size = 14, hjust = .5,face = "bold.italic")) +guides(color="none",fill="none")
```

```{r}
sample.map
```